---
- name: Configuring the Access-Control Lists on R2
  hosts: R2
  gather_facts: false
  connection: local

  tasks:
    - name: Configuring the port for ACL
      ios_config:
        lines:
          - ip access-group 110 in
        parents: interface FastEthernet0/0

    - name: Create rules for Interface Fa0/0
      ios_config:
        lines:
          - access-list 110 deny icmp any any echo-reply
          - access-list 110 permit ip any any
        before: no access-list 110
        match: exact
        